apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-data
  namespace: java
spec:
  capacity:
    storage: 200Gi 
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /data
    server: 192.168.91.12
  persistentVolumeReclaimPolicy: Recycle 
