apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  name: jms-data
  namespace: jumpserver
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: storageclass-default
  volumeMode: Filesystem
  volumeName: local-pv-10
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi

