apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: local-pv-10
spec:
  accessModes:
  - ReadWriteOnce                                 #只允许一人读写
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jms-data
    namespace: jumpserver
  local:
    path: /opt/k8s-data/jms                      #存储路径
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker1.hqj.wwdt.com                 #指定使用主机存储
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storageclass-default         #绑定sc
  volumeMode: Filesystem
