# 创建一个k8s-cmdb项目Deployment，启动4个pod并对资源初始化及限制，配置存活探针和就绪探针对pod进行监控，配合restartPolicy策略一旦存活或就绪探针检查失败则会重启，使用滚动升级策略进行升级

# 配置容器使用资源监控（集群需部署Metrics模块），当cpu使用率（对pod而言）和内存使用率达到阈值时将自动扩容、收缩pod，pod数量依赖minReplicas和maxReplicas配置

# 配置wwdt项目Deployment的端口及暴露服务的方式

# 结合nginx-ingress配置域名绑定到pod，ingrees拥有自动发现功能,在就绪探针确认后自动将流量转发到新pod

kind: Deployment
apiVersion: apps/v1
metadata:
  name: hqj-service-zuul
  namespace: wwdt
  labels:
    k8s-app:  hqj-service-zuul
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: hqj-service-zuul
  template:
    metadata:
      name: hqj-service-zuul
      labels:
        k8s-app: hqj-service-zuul
    spec:
      imagePullSecrets:            # 私有仓库认证
        - name: harborsecret
      containers:
        - name: hqj-service-zuul
          image: 192.168.1.172/hqj-dev/service-zuul:v1.0.0
          resources:               # 资源分配以限制
            requests:
              cpu: 0.5
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1024Mi
          imagePullPolicy: IfNotPresent
          livenessProbe:
            tcpSocket:
              port: 8769
            initialDelaySeconds: 10  #在pod启动后延迟30启动存活探针
            timeoutSeconds: 3        #探针请求超时3秒
            periodSeconds: 30        #间隔30秒启动存活探针
            successThreshold: 1      #处于失败状态时，探测操作至少连续1次的成功才被视为检测通过
            failureThreshold: 3      #处于成功状态时，探测操作至少连续3次的失败才被视为检测不通过
          readinessProbe:            
            tcpSocket:
              port: 8769
            initialDelaySeconds: 10  # 就绪探针，就绪通过后才向pod传入流量
            timeoutSeconds: 3
            periodSeconds: 30
            successThreshold: 1      #处于失败状态时，探测操作至少连续1次的成功才被视为检测通过
            failureThreshold: 3      #处于成功状态时，探测操作至少连续3次的失败才被视为检测不通过
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler   
  strategy:
    type: RollingUpdate         #滚动升级策略
    rollingUpdate:
      maxUnavailable: 25%       #在滚动升级时最大无效pod数
      maxSurge: 25%             #最大激增pod数，也就是每次滚动的步长
  revisionHistoryLimit: 10      #滚动升级历史版本保留10
  progressDeadlineSeconds: 600  #如在升级过程中卡住（镜像拉取等问题,这个时候还没有明确的升级失败), 如果超过600秒后还是处于卡住状态则pod状态就为false
status:
  observedGeneration: 5
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-hqj-service-zuul
  namespace: wwdt
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hqj-service-zuul
  minReplicas: 1
  maxReplicas: 1  
  metrics:
  - type: Resource
    resource:                         # 超过cpu资源限制的70% 触发扩容
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:                         # 超过内存资源限制的70% 触发扩容
      name: memory            
      targetAverageUtilization: 70

---
kind: Service
apiVersion: v1
metadata:
  name: hqj-service-zuul
  namespace: wwdt
  labels:
    k8s-app: hqj-service-zuul
spec:
  ports:
    - name: service-zuul-8769
      protocol: TCP
      port: 8769
      targetPort: 8769
  selector:
    k8s-app: hqj-service-zuul
  type: ClusterIP
  sessionAffinity: None
 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hqj-service-zuul
  namespace: wwdt
spec:
  rules:
  - host: k8s.hqj.service-zuul.com
    http:
      paths:
      - backend:
          serviceName: hqj-service-zuul
          servicePort: 8769
        path: /