apiVersion: v1
kind: PersistentVolume          #创建基于nfs的pv
metadata:
  name: nfs-pv-1
spec:
  capacity:
    storage: 200Gi 
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /data
    server: 192.168.1.130
  persistentVolumeReclaimPolicy: Recycle 
  storageClassName: storageclass-default
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jms-data
    namespace: jumpserver

---
kind: PersistentVolumeClaim     #创建pvc
apiVersion: v1
metadata:
  name: jms-data
  namespace: jumpserver
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi